version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./static/uploads:/app/static/uploads
    environment:
      - DATABASE_URL=mysql+pymysql://meme_user:meme_password@db:3306/meme_db
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=meme_db
      - MYSQL_USER=meme_user
      - MYSQL_PASSWORD=meme_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: 